---
  - name: install PostgreSQL
    apt:
      pkg: "{{ item }}"
      state: present
      update_cache: yes
      cache_valid_time: 3600
    with_items:
      - postgresql
      - python-psycopg2
      - postgresql-contrib
      - postgresql-server-dev-9.5
